const hotel = [
  {
    id: 1,
    name: "RCE Theaters - 907 S Beckford Dr, Henderson, NC 27536",
    location: "8558 Pecan St",
    rent: "$7225",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "1 Bath",
    size: "732 sft",
    city: "New York"
  },
  {
    id: 2,
    name: "XYZ Apartments - 123 Main St, New York, NY 10001",
    location: "456 Elm St",
    rent: "$6500",
    room: "2 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "900 sft",
    city: "New York"
  },
  {
    id: 3,
    name: "Elegant Homes - 456 Oak St, New York, NY 10001",
    location: "789 Maple St",
    rent: "$8500",
    room: "4 Rooms",
    bed: "5 bed",
    bath: "3 Bath",
    size: "1200 sft",
    city: "New York"
  },
  {
    id: 4,
    name: "Luxury Suites - 123 Broadway St, New York, NY 10001",
    location: "1011 Elm St",
    rent: "$9500",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "2 Bath",
    size: "950 sft",
    city: "New York"
  },
  {
    id: 5,
    name: "Downtown Lofts - 456 Park Ave, New York, NY 10001",
    location: "789 Oak St",
    rent: "$7200",
    room: "2 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "850 sft",
    city: "New York"
  },
  {
    id: 6,
    name: "Metropolitan Residences - 789 5th Ave, New York, NY 10001",
    location: "1011 Oak St",
    rent: "$8800",
    room: "4 Rooms",
    bed: "4 bed",
    bath: "3 Bath",
    size: "1100 sft",
    city: "New York"
  },
  {
    id: 7,
    name: "Uptown Villas - 123 Central Park West, New York, NY 10001",
    location: "456 Maple St",
    rent: "$10500",
    room: "5 Rooms",
    bed: "5 bed",
    bath: "4 Bath",
    size: "1500 sft",
    city: "New York"
  },
  {
    id: 8,
    name: "Brooklyn Apartments - 456 Flatbush Ave, New York, NY 10001",
    location: "789 Elm St",
    rent: "$6300",
    room: "2 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "820 sft",
    city: "New York"
  },
  {
    id: 9,
    name: "Queens Residences - 789 Queens Blvd, New York, NY 10001",
    location: "1011 Maple St",
    rent: "$6800",
    room: "2 Rooms",
    bed: "2 bed",
    bath: "2 Bath",
    size: "800 sft",
    city: "New York"
  },
  {
    id: 10,
    name: "Seaside Apartments - 123 Marine Dr, Mumbai, MH 400020",
    location: "456 Palm St",
    rent: "₹15,000",
    room: "2 Rooms",
    bed: "2 bed",
    bath: "1 Bath",
    size: "700 sqft",
    city: "Mumbai"
  },
  {
    id: 11,
    name: "Harbor View Homes - 456 Gateway Dr, Mumbai, MH 400021",
    location: "789 Coral St",
    rent: "₹22,000",
    room: "3 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "900 sqft",
    city: "Mumbai"
  },
  {
    id: 12,
    name: "Palm Grove Residences - 789 Juhu Beach, Mumbai, MH 400049",
    location: "1011 Ocean St",
    rent: "₹30,000",
    room: "2 Rooms",
    bed: "2 bed",
    bath: "2 Bath",
    size: "800 sqft",
    city: "Mumbai"
  },
  {
    id: 13,
    name: "Metro Heights - 123 Bandra West, Mumbai, MH 400050",
    location: "456 Hilltop St",
    rent: "₹25,000",
    room: "2 Rooms",
    bed: "2 bed",
    bath: "1 Bath",
    size: "750 sqft",
    city: "Mumbai"
  },
  {
    id: 14,
    name: "Coastal Villas - 456 Colaba, Mumbai, MH 400005",
    location: "789 Shore St",
    rent: "₹28,000",
    room: "3 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "900 sqft",
    city: "Mumbai"
  },
  {
    id: 15,
    name: "Harmony Homes - 789 Andheri East, Mumbai, MH 400059",
    location: "1011 Park St",
    rent: "₹20,000",
    room: "2 Rooms",
    bed: "2 bed",
    bath: "2 Bath",
    size: "800 sqft",
    city: "Mumbai"
  },
  {
    id: 16,
    name: "Golden Sands Apartments - 123 Worli, Mumbai, MH 400018",
    location: "456 Dunes St",
    rent: "₹35,000",
    room: "3 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "950 sqft",
    city: "Mumbai"
  },
  {
    id: 17,
    name: "Marina Heights - 456 Marine Lines, Mumbai, MH 400002",
    location: "789 Pier St",
    rent: "₹32,000",
    room: "3 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "920 sqft",
    city: "Mumbai"
  },
  {
    id: 18,
    name: "Bayside Residences - 789 Nariman Point, Mumbai, MH 400021",
    location: "1011 Bay St",
    rent: "₹40,000",
    room: "4 Rooms",
    bed: "4 bed",
    bath: "3 Bath",
    size: "1100 sqft",
    city: "Mumbai"
  },
  {
    id: 19,
    name: "Eiffel Tower Views - 1 Rue de la Bourdonnais, Paris, 75007",
    location: "22 Champs-Élysées",
    rent: "€1,200",
    room: "2 Rooms",
    bed: "2 bed",
    bath: "1 Bath",
    size: "65 sqm",
    city: "Paris"
  },
  {
    id: 20,
    name: "Montmartre Hideaway - 18 Rue des Saules, Paris, 75018",
    location: "36 Place du Tertre",
    rent: "€950",
    room: "1 Room",
    bed: "1 bed",
    bath: "1 Bath",
    size: "45 sqm",
    city: "Paris"
  },
  {
    id: 21,
    name: "Louvre Luxury Apartment - 1 Quai François Mitterrand, Paris, 75001",
    location: "12 Rue de Rivoli",
    rent: "€1,800",
    room: "3 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "85 sqm",
    city: "Paris"
  },
  {
    id: 22,
    name: "Seine River Retreat - 15 Quai de Montebello, Paris, 75005",
    location: "30 Île de la Cité",
    rent: "€1,500",
    room: "2 Rooms",
    bed: "2 bed",
    bath: "1 Bath",
    size: "70 sqm",
    city: "Paris"
  },
  {
    id: 23,
    name: "Marais Chic Studio - 25 Rue Vieille du Temple, Paris, 75004",
    location: "40 Place des Vosges",
    rent: "€1,100",
    room: "1 Room",
    bed: "1 bed",
    bath: "1 Bath",
    size: "35 sqm",
    city: "Paris"
  },
  {
    id: 24,
    name: "Champs-Élysées Palace - 8 Avenue des Champs-Élysées, Paris, 75008",
    location: "16 Arc de Triomphe",
    rent: "€2,500",
    room: "4 Rooms",
    bed: "4 bed",
    bath: "2 Bath",
    size: "120 sqm",
    city: "Paris"
  },
  {
    id: 25,
    name: "Latin Quarter Loft - 3 Rue Soufflot, Paris, 75005",
    location: "18 Panthéon",
    rent: "€1,350",
    room: "2 Rooms",
    bed: "2 bed",
    bath: "1 Bath",
    size: "60 sqm",
    city: "Paris"
  },
  {
    id: 26,
    name: "Canal Saint-Martin Duplex - 27 Quai de Valmy, Paris, 75010",
    location: "52 Canal Saint-Martin",
    rent: "€1,250",
    room: "2 Rooms",
    bed: "2 bed",
    bath: "1 Bath",
    size: "55 sqm",
    city: "Paris"
  },
  {
    id: 27,
    name: "Eiffel Tower Retreat - 12 Quai de Grenelle, Paris, 75015",
    location: "28 Champ de Mars",
    rent: "€1,900",
    room: "3 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "75 sqm",
    city: "Paris"
  },
  {
    id: 28,
    name: "Covent Garden Loft - 7 Floral St, London WC2E 9DP, UK",
    location: "10 Trafalgar Square",
    rent: "£1,500",
    room: "2 Rooms",
    bed: "2 bed",
    bath: "1 Bath",
    size: "70 sqm",
    city: "London"
  },
  {
    id: 29,
    name: "Southbank Serenity - Riverside Building, London SE1 7PB, UK",
    location: "30 Southbank",
    rent: "£1,800",
    room: "3 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "85 sqm",
    city: "London"
  },
  {
    id: 30,
    name: "Notting Hill Hideaway - 45 Portobello Rd, London W11 3DG, UK",
    location: "18 Notting Hill Gate",
    rent: "£1,200",
    room: "2 Rooms",
    bed: "2 bed",
    bath: "1 Bath",
    size: "60 sqm",
    city: "London"
  },
  {
    id: 31,
    name: "Kensington Elegance - 21 Kensington Palace Gardens, London W8 4QY, UK",
    location: "35 Kensington High St",
    rent: "£2,500",
    room: "4 Rooms",
    bed: "4 bed",
    bath: "2 Bath",
    size: "110 sqm",
    city: "London"
  },
  {
    id: 32,
    name: "Shoreditch Studio - 1 Kingsland Rd, London E2 8AA, UK",
    location: "24 Shoreditch High St",
    rent: "£1,100",
    room: "1 Room",
    bed: "1 bed",
    bath: "1 Bath",
    size: "40 sqm",
    city: "London"
  },
  {
    id: 33,
    name: "Mayfair Luxury Apartment - 5 Hamilton Mews, London W1J 7DZ, UK",
    location: "12 Bond St",
    rent: "£3,000",
    room: "5 Rooms",
    bed: "5 bed",
    bath: "3 Bath",
    size: "150 sqm",
    city: "London"
  },
  {
    id: 34,
    name: "Camden Townhouse - 10 Arlington Rd, London NW1 7HU, UK",
    location: "28 Camden High St",
    rent: "£1,700",
    room: "3 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "80 sqm",
    city: "London"
  },
  {
    id: 35,
    name: "Bayswater Studio - 24 Kensington Gardens Square, London W2 4BA, UK",
    location: "15 Queensway",
    rent: "£1,000",
    room: "1 Room",
    bed: "1 bed",
    bath: "1 Bath",
    size: "30 sqm",
    city: "London"
  },
  {
    id: 36,
    name: "Westminster Views - 20 Dean Bradley St, London SW1P 4DQ, UK",
    location: "10 Victoria St",
    rent: "£2,200",
    room: "4 Rooms",
    bed: "4 bed",
    bath: "2 Bath",
    size: "100 sqm",
    city: "London"
  }
]

export default hotel;